version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17 # 使用官方推荐的 Node 镜像
    steps:
      - checkout

      - run:
          name: Print Node/NPM/Yarn Versions
          command: |
            node -v
            npm -v
            yarn -v

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Build project
          command: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: main # ✅ 确保与你实际推送的分支一致（main 分支）
