jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: 安装系统依赖(Cypress 需要)
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              libgtk2.0-0 \
              libgtk-3-0 \
              libgbm-dev \
              libnotify-dev \
              libgconf-2-4 \
              libnss3 \
              libxss1 \
              libasound2 \
              libxtst6 \
              xauth \
              xvfb
      - run:
          name: 安装依赖
          command: npm install
      - run:
          name: 安装 Cypress
          command: npx cypress install
      - run:
          name: 编译项目
          command: npm run build
      - run:
          name: 启动服务并执行 Cypress E2E 测试
          command: xvfb-run npm run test:e2e

workflows:
  version: 2
  test_workflow:
    jobs:
      - build_and_test
